/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CardLayout;

import java.awt.CardLayout;

/**
 *
 * @author usuario
 */
public class IntfCardLayout extends javax.swing.JPanel {

    /**
     * Creates new form IntfCardLayout
     */
    public IntfCardLayout() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpBotons = new javax.swing.ButtonGroup();
        pnlEsquerda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        pnlCentral = new javax.swing.JPanel();
        pnlCheckBoxes = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        pnlCombos = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        pnlBotons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlEsquerda.setBackground(new java.awt.Color(255, 255, 102));
        pnlEsquerda.setPreferredSize(new java.awt.Dimension(150, 300));
        pnlEsquerda.setLayout(new javax.swing.BoxLayout(pnlEsquerda, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Escolle o panel");
        pnlEsquerda.add(jLabel1);

        btngrpBotons.add(jRadioButton1);
        jRadioButton1.setLabel("Botón");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        pnlEsquerda.add(jRadioButton1);

        btngrpBotons.add(jRadioButton2);
        jRadioButton2.setLabel("Combos");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        pnlEsquerda.add(jRadioButton2);

        btngrpBotons.add(jRadioButton3);
        jRadioButton3.setLabel("Checkboxes");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        pnlEsquerda.add(jRadioButton3);

        add(pnlEsquerda, java.awt.BorderLayout.WEST);

        pnlCentral.setLayout(new java.awt.CardLayout());

        pnlCheckBoxes.setBackground(new java.awt.Color(51, 153, 0));

        jCheckBox1.setText("Check 1");
        pnlCheckBoxes.add(jCheckBox1);

        jCheckBox2.setText("Check 2");
        pnlCheckBoxes.add(jCheckBox2);

        jCheckBox3.setText("Check 3");
        pnlCheckBoxes.add(jCheckBox3);

        pnlCentral.add(pnlCheckBoxes, "CHECKBOXES");

        pnlCombos.setBackground(new java.awt.Color(0, 51, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combo 1", "Item 2", "Item 3", "Item 4" }));
        pnlCombos.add(jComboBox1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combo 2", "Item 2", "Item 3", "Item 4" }));
        pnlCombos.add(jComboBox2);

        pnlCentral.add(pnlCombos, "COMBOS");

        pnlBotons.setBackground(new java.awt.Color(255, 0, 0));

        jButton1.setText("Boton 1");
        pnlBotons.add(jButton1);

        jButton2.setText("Boton 2");
        pnlBotons.add(jButton2);

        jButton3.setText("Boton 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlBotons.add(jButton3);

        pnlCentral.add(pnlBotons, "BOTONS");

        add(pnlCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout paneisLayout = (CardLayout)this.pnlCentral.getLayout();
        paneisLayout.show(this.pnlCentral, "BOTONS");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout paneisLayout = (CardLayout)this.pnlCentral.getLayout();
        paneisLayout.show(this.pnlCentral, "CHECKBOXES");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout paneisLayout=(CardLayout)this.pnlCentral.getLayout();
        paneisLayout.show(this.pnlCentral, "COMBOS");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpBotons;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel pnlBotons;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlCheckBoxes;
    private javax.swing.JPanel pnlCombos;
    private javax.swing.JPanel pnlEsquerda;
    // End of variables declaration//GEN-END:variables

}
