GET http://localhost:80/clientes/rest.php/clientes

###
POST http://localhost:80/clientes/rest.php/insertarCliente
Content-Type: application/x-www-form-urlencoded

nombre=Manuel&apellidos=Martinez&codProvincia=3&vip=1