/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author DAM 2
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        DlgValidacionUsuario dlgValidacionUsuario = new DlgValidacionUsuario(this, true);
        dlgValidacionUsuario.setVisible(true);
        setSize(1200, 900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpEscritorio = new javax.swing.JDesktopPane();
        brmnuBarraMenu = new javax.swing.JMenuBar();
        mnuOpcions = new javax.swing.JMenu();
        mnuAltas = new javax.swing.JMenu();
        mnuitCansRazas = new javax.swing.JMenuItem();
        mnuitPropietarios = new javax.swing.JMenuItem();
        mnuitXestionVacinacions = new javax.swing.JMenuItem();
        mnuspSeparador1 = new javax.swing.JPopupMenu.Separator();
        mnuPerrucaria = new javax.swing.JMenu();
        mnuitNovaCitaPerrucaria = new javax.swing.JMenuItem();
        mnuspSeparador3 = new javax.swing.JPopupMenu.Separator();
        mnuOperacions = new javax.swing.JMenu();
        mnuiNovaOperacion = new javax.swing.JMenuItem();
        mnuiListadoBaixaOperacions = new javax.swing.JMenuItem();
        mnuspSeparador2 = new javax.swing.JPopupMenu.Separator();
        mnuitSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuImprimirFacturas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xestión clínica");
        getContentPane().add(dtpEscritorio, java.awt.BorderLayout.CENTER);

        mnuOpcions.setText("Opcións");

        mnuAltas.setText("Altas");

        mnuitCansRazas.setText("Cans/Razas");
        mnuitCansRazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitCansRazasActionPerformed(evt);
            }
        });
        mnuAltas.add(mnuitCansRazas);

        mnuitPropietarios.setText("Propietarios");
        mnuitPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitPropietariosActionPerformed(evt);
            }
        });
        mnuAltas.add(mnuitPropietarios);

        mnuOpcions.add(mnuAltas);

        mnuitXestionVacinacions.setText("Xestión vacinacións");
        mnuitXestionVacinacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitXestionVacinacionsActionPerformed(evt);
            }
        });
        mnuOpcions.add(mnuitXestionVacinacions);
        mnuOpcions.add(mnuspSeparador1);

        mnuPerrucaria.setText("Perrucaría");

        mnuitNovaCitaPerrucaria.setText("Nova cita perrucaría");
        mnuitNovaCitaPerrucaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitNovaCitaPerrucariaActionPerformed(evt);
            }
        });
        mnuPerrucaria.add(mnuitNovaCitaPerrucaria);

        mnuOpcions.add(mnuPerrucaria);
        mnuOpcions.add(mnuspSeparador3);

        mnuOperacions.setText("Xestión de operacións");

        mnuiNovaOperacion.setText("Nova operación");
        mnuiNovaOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNovaOperacionActionPerformed(evt);
            }
        });
        mnuOperacions.add(mnuiNovaOperacion);

        mnuiListadoBaixaOperacions.setText("Baixas e listados de operacións");
        mnuiListadoBaixaOperacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListadoBaixaOperacionsActionPerformed(evt);
            }
        });
        mnuOperacions.add(mnuiListadoBaixaOperacions);

        mnuOpcions.add(mnuOperacions);
        mnuOpcions.add(mnuspSeparador2);

        mnuitSair.setText("Saír");
        mnuitSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitSairActionPerformed(evt);
            }
        });
        mnuOpcions.add(mnuitSair);

        brmnuBarraMenu.add(mnuOpcions);

        jMenu1.setText("Facturación");

        mnuImprimirFacturas.setText("Imprimir Facturas");
        mnuImprimirFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImprimirFacturasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuImprimirFacturas);

        brmnuBarraMenu.add(jMenu1);

        setJMenuBar(brmnuBarraMenu);

        setBounds(0, 0, 1057, 741);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuImprimirFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImprimirFacturasActionPerformed
        if (XestorDeXanelas.podeseAbrirIFrmImprimirFacturas()) {
            IFrmImprimirFacturas iFrmImprimirFacturas = new IFrmImprimirFacturas(this);
            dtpEscritorio.add(iFrmImprimirFacturas);
            iFrmImprimirFacturas.show();
            XestorDeXanelas.abrirIFrmImprimirFacturas();
        }
    }//GEN-LAST:event_mnuImprimirFacturasActionPerformed

    private void mnuitSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuitSairActionPerformed

    private void mnuiListadoBaixaOperacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListadoBaixaOperacionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuiListadoBaixaOperacionsActionPerformed

    private void mnuiNovaOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNovaOperacionActionPerformed
        // TODO add your handling code here:
        if (XestorDeXanelas.podeseAbrirIFrmAltaOperacions()) {
            IFrmAltaOperacions iFrmAltaOperacions = new IFrmAltaOperacions();
            dtpEscritorio.add(iFrmAltaOperacions);
            iFrmAltaOperacions.show();
            XestorDeXanelas.abrirIFrmAltaOperacions();
        }

    }//GEN-LAST:event_mnuiNovaOperacionActionPerformed

    private void mnuitXestionVacinacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitXestionVacinacionsActionPerformed
        // TODO add your handling code here:
        if (XestorDeXanelas.podeseAbrirIFrmXestionVacinacions()) {
            IFrmXestionVacinacions iFrmXestionVacinacions = new IFrmXestionVacinacions();
            dtpEscritorio.add(iFrmXestionVacinacions);
            iFrmXestionVacinacions.show();
            XestorDeXanelas.abrirIFrmXestionVacinacions();
        }
    }//GEN-LAST:event_mnuitXestionVacinacionsActionPerformed

    private void mnuitPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitPropietariosActionPerformed
        // TODO add your handling code here:
        IFrmAltaPropietarios iFrmAltaPropietarios = new IFrmAltaPropietarios();
        dtpEscritorio.add(iFrmAltaPropietarios);
        iFrmAltaPropietarios.show();
    }//GEN-LAST:event_mnuitPropietariosActionPerformed

    private void mnuitCansRazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitCansRazasActionPerformed
        // TODO add your handling code here:
        IFrmAltaCansRazas iFrmAltaCansRazas = new IFrmAltaCansRazas();
        dtpEscritorio.add(iFrmAltaCansRazas);
        iFrmAltaCansRazas.show();
    }//GEN-LAST:event_mnuitCansRazasActionPerformed

    private void mnuitNovaCitaPerrucariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitNovaCitaPerrucariaActionPerformed
        // TODO add your handling code here:
        if (XestorDeXanelas.podeseAbrirIFrmNovaCitaPerrucaria()) {
            IFrmNovaCitaPerrucaria iFrmNovaCitaPerrucaria = new IFrmNovaCitaPerrucaria();
            dtpEscritorio.add(iFrmNovaCitaPerrucaria);
            iFrmNovaCitaPerrucaria.setSize(600, 250);
            iFrmNovaCitaPerrucaria.show();
            XestorDeXanelas.abrirIFrmNovaCitaPerrucaria();
        } else {
            JOptionPane.showMessageDialog(this, "Non é posible abrir máis xanelas deste tipo");
            return;
        }
    }//GEN-LAST:event_mnuitNovaCitaPerrucariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar brmnuBarraMenu;
    private javax.swing.JDesktopPane dtpEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu mnuAltas;
    private javax.swing.JMenuItem mnuImprimirFacturas;
    private javax.swing.JMenu mnuOpcions;
    private javax.swing.JMenu mnuOperacions;
    private javax.swing.JMenu mnuPerrucaria;
    private javax.swing.JMenuItem mnuiListadoBaixaOperacions;
    private javax.swing.JMenuItem mnuiNovaOperacion;
    private javax.swing.JMenuItem mnuitCansRazas;
    private javax.swing.JMenuItem mnuitNovaCitaPerrucaria;
    private javax.swing.JMenuItem mnuitPropietarios;
    private javax.swing.JMenuItem mnuitSair;
    private javax.swing.JMenuItem mnuitXestionVacinacions;
    private javax.swing.JPopupMenu.Separator mnuspSeparador1;
    private javax.swing.JPopupMenu.Separator mnuspSeparador2;
    private javax.swing.JPopupMenu.Separator mnuspSeparador3;
    // End of variables declaration//GEN-END:variables
}
