/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import bd.ConsultasSQL;
import clases.Propietario;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM 2 
 */
public class IFrmAltaPropietarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmAltaPropietarios
     */
    public IFrmAltaPropietarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtApelido1 = new javax.swing.JTextField();
        txtEMail = new javax.swing.JTextField();
        txtApelido2 = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        pnlBotons = new javax.swing.JPanel();
        btnGardar = new javax.swing.JButton();
        btnPechar = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Novo propietario");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Apelido 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Apelido 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("EMail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtNome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(txtDNI, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtApelido1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtEMail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        getContentPane().add(txtApelido2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(txtTelefono, gridBagConstraints);

        pnlBotons.setLayout(new javax.swing.BoxLayout(pnlBotons, javax.swing.BoxLayout.X_AXIS));

        btnGardar.setText("Gardar");
        btnGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGardarActionPerformed(evt);
            }
        });
        pnlBotons.add(btnGardar);

        btnPechar.setText("Pechar");
        btnPechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPecharActionPerformed(evt);
            }
        });
        pnlBotons.add(btnPechar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(pnlBotons, gridBagConstraints);

        setBounds(0, 0, 601, 190);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnPecharActionPerformed

    private void btnGardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGardarActionPerformed
        // TODO add your handling code here:
        String DNI=txtDNI.getText().trim();
        if(DNI.compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Debe indicar o DNI", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        switch(ConsultasSQL.existeDNI(DNI))
        {
            case 1: JOptionPane.showMessageDialog(this, "O DNI indicado xa existe", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
           case 2: JOptionPane.showMessageDialog(this, "Ocurreu un erro de base de datos ao comprobar a existencia do DNI. Erro -3. Póñase en contacto co administrador", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
        }
        
        String nome=txtNome.getText().trim();
        if(nome.compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Debe indicar o Nome", "Atención", JOptionPane.WARNING_MESSAGE);
            return;            
        }        
        
        String ap1=txtApelido1.getText().trim();
        if(ap1.compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Debe indicar o primeiro apelido", "Atención", JOptionPane.WARNING_MESSAGE);
            return;            
        }                
        
        String ap2=txtApelido2.getText().trim();
        if(ap2.compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Debe indicar o segundo apelido", "Atención", JOptionPane.WARNING_MESSAGE);
            return;            
        }                        
        
        String tlf=txtTelefono.getText().trim();
        if(tlf.compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Debe indicar o teléfono", "Atención", JOptionPane.WARNING_MESSAGE);
            return;            
        }   
        
        String email=txtEMail.getText().trim();
        if(email.compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Debe indicar o email", "Atención", JOptionPane.WARNING_MESSAGE);
            return;            
        }  
        
        Propietario propietario=new Propietario(DNI, nome, ap1, ap2, tlf, email);
        if(ConsultasSQL.insertarPropietario(propietario)==-1)
        {
            JOptionPane.showMessageDialog(this, "Ocurreu un erro de base de datos ao insertar ao propietario. Error -4. Póñase en contacto co administrador", "Atención", JOptionPane.WARNING_MESSAGE);
            return;            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Propietario gardado", "Éxito", JOptionPane.INFORMATION_MESSAGE);            
        }
        dispose();
    }//GEN-LAST:event_btnGardarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGardar;
    private javax.swing.JButton btnPechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlBotons;
    private javax.swing.JTextField txtApelido1;
    private javax.swing.JTextField txtApelido2;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables


}
