/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JCheckBox;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class IntfJCheckBox extends javax.swing.JPanel {

    /**
     * Creates new form IntfJCheckBox
     */
    public IntfJCheckBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        pnlVacinasAplicadas = new javax.swing.JPanel();
        chkTetano = new javax.swing.JCheckBox();
        chkHepatite = new javax.swing.JCheckBox();
        chkSarampelo = new javax.swing.JCheckBox();
        btnGardar = new javax.swing.JButton();

        setToolTipText("");

        lblNome.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        pnlVacinasAplicadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Vacinas aplicadas"));
        pnlVacinasAplicadas.setToolTipText("");

        chkTetano.setText("Tétano");
        chkTetano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTetanoActionPerformed(evt);
            }
        });

        chkHepatite.setText("Hepatite");

        chkSarampelo.setText("Sarampelo");

        javax.swing.GroupLayout pnlVacinasAplicadasLayout = new javax.swing.GroupLayout(pnlVacinasAplicadas);
        pnlVacinasAplicadas.setLayout(pnlVacinasAplicadasLayout);
        pnlVacinasAplicadasLayout.setHorizontalGroup(
            pnlVacinasAplicadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVacinasAplicadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkTetano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkHepatite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkSarampelo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVacinasAplicadasLayout.setVerticalGroup(
            pnlVacinasAplicadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVacinasAplicadasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlVacinasAplicadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTetano)
                    .addComponent(chkHepatite)
                    .addComponent(chkSarampelo))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnGardar.setText("Gardar");
        btnGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlVacinasAplicadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnGardar)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlVacinasAplicadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGardar)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnGardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGardarActionPerformed
        // TODO add your handling code here:
        String nome=txtNome.getText().trim();
        
        if (nome.compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Debe indicar o nome");
            return;
        }
        
        //Nova Vacinacion
        Vacinacion vacinacion=new Vacinacion(nome);

        //Recollida de datos dos JCheckBoxes
        vacinacion.setTetano(chkTetano.isSelected());
        vacinacion.setHepatite(chkHepatite.isSelected());
        vacinacion.setSarampelo(chkSarampelo.isSelected());

        //Insertar o obxeto creado na BD
        //Non é parte desta unidade didactica

        JOptionPane.showMessageDialog(this, "Rexistro gardado correctamente");
    }//GEN-LAST:event_btnGardarActionPerformed

    private void chkTetanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTetanoActionPerformed
        
    }//GEN-LAST:event_chkTetanoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGardar;
    private javax.swing.JCheckBox chkHepatite;
    private javax.swing.JCheckBox chkSarampelo;
    private javax.swing.JCheckBox chkTetano;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlVacinasAplicadas;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
