USE BDEmpresa;

-- COMPROBAR SI EXISTE LA TABLA VEHICULOS Y BORRARLA EN CASO DE QUE EXISTA
IF DB_ID('VEHICULOS') IS NOT NULL
    BEGIN
        SELECT 'LA TABLA VEHICULOS YA EXISTE, SE VA A BORRAR' AS MENSAJE
        DROP TABLE VEHICULOS
    END
ELSE
    SELECT 'LA TABLA VEHICULOS NO EXISTE, SE VA A CREAR' AS MENSAJE

CREATE TABLE VEHICULOS
(

    codVehiculo VARCHAR(25) IDENTITY (1,1) NOT NULL,
    Matricula   CHAR(8)                    NOT NULL,
    Marca       VARCHAR(25)                NOT NULL,
    Modelo      VARCHAR(15)                NOT NULL,
    Combustible CHAR(1)                    NULL
)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT PK_Vehiculos_codVehiculo PRIMARY KEY (codVehiculo)

-- COMPROBAR SI EXISTE LA TABLA VEHICULOS_RENTING Y BORRARLA EN CASO DE QUE EXISTA
IF DB_ID('VEHICULOS_RENTING') IS NOT NULL
    BEGIN
        SELECT 'LA TABLA VEHICULOS_RENTING YA EXISTE, SE VA A BORRAR' AS MENSAJE
        DROP TABLE VEHICULOS_RENTING
    END
ELSE
    SELECT 'LA TABLA VEHICULOS_RENTING NO EXISTE, SE VA A CREAR' AS MENSAJE

CREATE TABLE VEHICULOS_RENTING
(

    Matricula      CHAR(8)     NOT NULL,
    fechaInicio    DATETIME    NOT NULL,
    mesesAlquilado VARCHAR(25) NOT NULL
)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT PK_VehiculosRenting_Matricula PRIMARY KEY (Matricula)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT FK_VehiculosRenting_Matricula FOREIGN KEY (Matricula) REFERENCES VEHICULOS (Matricula)

-- COMPROBAR SI EXISTE LA TABLA VEHICULOS_PROPIOS Y BORRARLA EN CASO DE QUE EXISTA
IF DB_ID('VEHICULOS_PROPIOS') IS NOT NULL
    BEGIN
        SELECT 'LA TABLA VEHICULOS_PROPIOS YA EXISTE, SE VA A BORRAR' AS MENSAJE
        DROP TABLE VEHICULOS_PROPIOS
    END
ELSE
    SELECT 'LA TABLA VEHICULOS_PROPIOS NO EXISTE, SE VA A CREAR' AS MENSAJE

CREATE TABLE VEHICULOS_PROPIOS
(

    Matricula    CHAR(8)          NOT NULL,
    fechaCompra  DATETIME         NOT NULL,
    precioPagado DOUBLE PRECISION NOT NULL
)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT PK_VehiculosPropios_Matricula PRIMARY KEY (Matricula)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT FK_VehiculosPropios_Matricula FOREIGN KEY (Matricula) REFERENCES VEHICULOS (Matricula)