USE BDEmpresa;

-- COMPROBAR SI EXISTE LA TABLA VEHICULOS Y BORRARLA EN CASO DE QUE EXISTA
IF DB_ID('VEHICULOS') IS NOT NULL
    BEGIN
        SELECT 'LA TABLA VEHICULOS YA EXISTE, SE VA A BORRAR' AS MENSAJE
        DROP TABLE VEHICULOS
    END
ELSE
    SELECT 'LA TABLA VEHICULOS NO EXISTE, SE VA A CREAR' AS MENSAJE

CREATE TABLE VEHICULOS
(
    codVehiculo INT IDENTITY (1,1) NOT NULL,
    Matricula   CHAR(8)            NOT NULL,
    Marca       VARCHAR(25)        NOT NULL,
    Modelo      VARCHAR(15)        NOT NULL,
    Combustible CHAR(1)            NOT NULL
)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT PK_Vehiculos_codVehiculo PRIMARY KEY (codVehiculo)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT UQ_Vehiculos_Combustible UNIQUE (Matricula)

ALTER TABLE VEHICULOS
    ADD CONSTRAINT CK_Vehiculos_Matricula CHECK (Matricula LIKE '[0-9][0-9][0-9][0-9] [A-Z][A-Z][A-Z]')

ALTER TABLE VEHICULOS
    ADD CONSTRAINT CK_Vehiculos_Combustible CHECK (Combustible IN ('G', 'D'))

-- COMPROBAR SI EXISTE LA TABLA VEHICULOS_RENTING Y BORRARLA EN CASO DE QUE EXISTA
IF DB_ID('VEHICULOS_RENTING') IS NOT NULL
    BEGIN
        SELECT 'LA TABLA VEHICULOS_RENTING YA EXISTE, SE VA A BORRAR' AS MENSAJE
        DROP TABLE VEHICULOS_RENTING
    END
ELSE
    SELECT 'LA TABLA VEHICULOS_RENTING NO EXISTE, SE VA A CREAR' AS MENSAJE

CREATE TABLE VEHICULOS_RENTING
(
    codVehiculo    INT              NOT NULL,
    fechaInicio    DATE             NOT NULL,
    mesesAlquilado TINYINT          NOT NULL,
    precio         DOUBLE PRECISION NOT NULL
)

ALTER TABLE VEHICULOS_RENTING
    ADD CONSTRAINT PK_Vehiculos_codVehiculo PRIMARY KEY (codVehiculo)

ALTER TABLE VEHICULOS_RENTING
    ADD CONSTRAINT FK_Vehiculos_codVehiculo FOREIGN KEY (codVehiculo) REFERENCES VEHICULOS (codVehiculo)

-- COMPROBAR SI EXISTE LA TABLA VEHICULOS_PROPIOS Y BORRARLA EN CASO DE QUE EXISTA
IF DB_ID('VEHICULOS_PROPIOS') IS NOT NULL
    BEGIN
        SELECT 'LA TABLA VEHICULOS_PROPIOS YA EXISTE, SE VA A BORRAR' AS MENSAJE
        DROP TABLE VEHICULOS_PROPIOS
    END
ELSE
    SELECT 'LA TABLA VEHICULOS_PROPIOS NO EXISTE, SE VA A CREAR' AS MENSAJE

CREATE TABLE VEHICULOS_PROPIOS
(
    codVehiculo INT              NOT NULL,
    fechaCompra DATE             NOT NULL,
    precio      DOUBLE PRECISION NOT NULL
)

ALTER TABLE VEHICULOS_PROPIOS
    ADD CONSTRAINT PK_Vehiculos_codVehiculo PRIMARY KEY (codVehiculo)

ALTER TABLE VEHICULOS_PROPIOS
    ADD CONSTRAINT FK_Vehiculos_codVehiculo FOREIGN KEY (codVehiculo) REFERENCES VEHICULOS (codVehiculo)