/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM IES Chan do Monte
 */
public class FrmPrincipal extends javax.swing.JFrame {

//    private boolean identificado=false;
//    public void activarAplicacion()
//    {
//        identificado=true;
//    }
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        DlgValidacionUsuario dlgValidacionUsuario=new DlgValidacionUsuario(this, true);
        dlgValidacionUsuario.setVisible(true);
        //if(!identificado) System.exit(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpEscritorio = new javax.swing.JDesktopPane();
        brmnuBarraMenu = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuAltas = new javax.swing.JMenu();
        mnuitCansRazas = new javax.swing.JMenuItem();
        mnuitPropietarios = new javax.swing.JMenuItem();
        mnuPropietarios = new javax.swing.JMenuItem();
        mnuspSeparador1 = new javax.swing.JPopupMenu.Separator();
        mnuitSair = new javax.swing.JMenuItem();
        mnuXestión = new javax.swing.JMenu();
        mnuitXestionVacinacions = new javax.swing.JMenuItem();
        mnuFacturacion = new javax.swing.JMenu();
        mnuImprimir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xestión clínica");
        getContentPane().add(dtpEscritorio, java.awt.BorderLayout.CENTER);

        mnuArquivo.setText("Arquivo");

        mnuAltas.setText("Altas");

        mnuitCansRazas.setText("Cans/Razas");
        mnuitCansRazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitCansRazasActionPerformed(evt);
            }
        });
        mnuAltas.add(mnuitCansRazas);

        mnuitPropietarios.setText("Propietarios");
        mnuitPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitPropietariosActionPerformed(evt);
            }
        });
        mnuAltas.add(mnuitPropietarios);

        mnuArquivo.add(mnuAltas);

        mnuPropietarios.setText("Propietarios");
        mnuPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPropietariosActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuPropietarios);
        mnuArquivo.add(mnuspSeparador1);

        mnuitSair.setText("Saír");
        mnuitSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuitSair);

        brmnuBarraMenu.add(mnuArquivo);

        mnuXestión.setText("Xestión");
        mnuXestión.setActionCommand("Xestion");

        mnuitXestionVacinacions.setText("Xestión vacinacións");
        mnuitXestionVacinacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitXestionVacinacionsActionPerformed(evt);
            }
        });
        mnuXestión.add(mnuitXestionVacinacions);

        brmnuBarraMenu.add(mnuXestión);

        mnuFacturacion.setText("Facturación");

        mnuImprimir.setText("Imprimir");
        mnuImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImprimirActionPerformed(evt);
            }
        });
        mnuFacturacion.add(mnuImprimir);

        brmnuBarraMenu.add(mnuFacturacion);

        setJMenuBar(brmnuBarraMenu);

        setBounds(0, 0, 1023, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuitSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuitSairActionPerformed

    private void mnuitPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitPropietariosActionPerformed
        // TODO add your handling code here:
        IFrmAltaPropietarios iFrmAltaPropietarios=new IFrmAltaPropietarios();
        dtpEscritorio.add(iFrmAltaPropietarios);
        iFrmAltaPropietarios.show();
    }//GEN-LAST:event_mnuitPropietariosActionPerformed

    private void mnuitCansRazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitCansRazasActionPerformed
        // TODO add your handling code here:
        IFrmAltaCansRazas iFrmAltaCansRazas=new IFrmAltaCansRazas();
        dtpEscritorio.add(iFrmAltaCansRazas);
        iFrmAltaCansRazas.show();        
    }//GEN-LAST:event_mnuitCansRazasActionPerformed

    private void mnuitXestionVacinacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitXestionVacinacionsActionPerformed
        // TODO add your handling code here:
        if(XestorDeXanelas.podeseAbrirIFrmXestionVacinacions())
        {
            IFrmXestionVacinacions iFrmXestionVacinacions=new IFrmXestionVacinacions();
            dtpEscritorio.add(iFrmXestionVacinacions);
            iFrmXestionVacinacions.show();                            
            XestorDeXanelas.abrirIFrmXestionVacinacions();
        }        
    }//GEN-LAST:event_mnuitXestionVacinacionsActionPerformed

    private void mnuImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImprimirActionPerformed
         if(XestorDeXanelas.podeseAbrirIFrmImprimirFacturas())
        {
             try {
                 IFrmImprimirFacturas iFrmImprimirFacturas=new IFrmImprimirFacturas();
                 dtpEscritorio.add(iFrmImprimirFacturas);
                 iFrmImprimirFacturas.show();
                 XestorDeXanelas.abrirIFrmImprimirFacturas();
             } catch (MalformedURLException ex) {
                 Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             } catch (HelpSetException ex) {
                 Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }
        } 
         /*
        if(XestorDeXanelas.podeseAbrirIFrmImprimirFacturas())
        {
            IFrmImprimirFacturas iFrmImprimirFacturas=new IFrmImprimirFacturas();
            dtpEscritorio.add(iFrmImprimirFacturas);
            iFrmImprimirFacturas.show();                            
            XestorDeXanelas.abrirIFrmImprimirFacturas();
        } 
         */
    }//GEN-LAST:event_mnuImprimirActionPerformed

    private void mnuPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPropietariosActionPerformed
        if (XestorDeXanelas.podeseAbrirIFrmListadoPropietarios()) {
            IFrameListadoPropietarios iFrameListadoPropietrios = new IFrameListadoPropietarios();
            dtpEscritorio.add(iFrameListadoPropietrios);
            iFrameListadoPropietrios.show();
            XestorDeXanelas.abrirIFrmListadoPropietarios();
        } else {
            JOptionPane.showMessageDialog(this, "Xa hai unha ventá de listado de propietarios aberta.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPropietariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar brmnuBarraMenu;
    private javax.swing.JDesktopPane dtpEscritorio;
    private javax.swing.JMenu mnuAltas;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuFacturacion;
    private javax.swing.JMenuItem mnuImprimir;
    private javax.swing.JMenuItem mnuPropietarios;
    private javax.swing.JMenu mnuXestión;
    private javax.swing.JMenuItem mnuitCansRazas;
    private javax.swing.JMenuItem mnuitPropietarios;
    private javax.swing.JMenuItem mnuitSair;
    private javax.swing.JMenuItem mnuitXestionVacinacions;
    private javax.swing.JPopupMenu.Separator mnuspSeparador1;
    // End of variables declaration//GEN-END:variables
}
