/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Mascara;

/**
 *
 * @author usuario
 */
public class IntfMascara extends javax.swing.JPanel {

    /**
     * Creates new form IntfMascara
     */
    public IntfMascara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Etiqueta");
        add(jLabel1);

        jButton1.setText("Botón");
        add(jButton1);

        jTextField1.setText("Caixa de texto");
        add(jTextField1);

        jRadioButton1.setText("Botón de opción");
        add(jRadioButton1);

        jCheckBox1.setText("Casilla de verificación");
        add(jCheckBox1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combo", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
