/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NullLayout;

/**
 *
 * @author usuario
 */
public class IntfNullLayout extends javax.swing.JPanel {

    /**
     * Creates new form IntfNullLayout
     */
    public IntfNullLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Boton 1");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 24, -1, -1));

        jButton2.setText("Boton 2");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jButton3.setText("Boton 3");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
