/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.awt.event.ItemEvent;

/**
 *
 * @author usuario
 */
public class IFrmXestionVacinacions extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmXestionVacinacions
     */
    public IFrmXestionVacinacions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPropietario = new javax.swing.JLabel();
        lblCan = new javax.swing.JLabel();
        lblChip = new javax.swing.JLabel();
        pnlVacinasAplicadas = new javax.swing.JPanel();
        scpVacinacions = new javax.swing.JScrollPane();
        tblVacinacions = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        pnlAplicarVacina = new javax.swing.JPanel();
        lblVacina = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblObservacions = new javax.swing.JLabel();
        cmbVacinas = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JTextField();
        txtObservacions = new javax.swing.JTextField();
        btnVacinar = new javax.swing.JButton();
        pnlBotons = new javax.swing.JPanel();
        btnPechar = new javax.swing.JButton();
        cmbPropietarios = new javax.swing.JComboBox<>();
        cmbCans = new javax.swing.JComboBox<>();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblPropietario.setText("Propietario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblPropietario, gridBagConstraints);

        lblCan.setText("Can");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblCan, gridBagConstraints);

        lblChip.setText("CHIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblChip, gridBagConstraints);

        pnlVacinasAplicadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Vacinas aplicadas"));
        pnlVacinasAplicadas.setLayout(new java.awt.GridBagLayout());

        tblVacinacions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vacina", "Num. total doses", "Dose aplicada", "Data", "Observacións"
            }
        ));
        scpVacinacions.setViewportView(tblVacinacions);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlVacinasAplicadas.add(scpVacinacions, gridBagConstraints);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlVacinasAplicadas.add(btnEliminar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(pnlVacinasAplicadas, gridBagConstraints);

        pnlAplicarVacina.setBorder(javax.swing.BorderFactory.createTitledBorder("Aplicar vacina"));
        pnlAplicarVacina.setLayout(new java.awt.GridBagLayout());

        lblVacina.setText("Vacina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAplicarVacina.add(lblVacina, gridBagConstraints);

        lblData.setText("Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAplicarVacina.add(lblData, gridBagConstraints);

        lblObservacions.setText("Observacions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAplicarVacina.add(lblObservacions, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAplicarVacina.add(cmbVacinas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAplicarVacina.add(txtData, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAplicarVacina.add(txtObservacions, gridBagConstraints);

        btnVacinar.setText("Vacinar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAplicarVacina.add(btnVacinar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(pnlAplicarVacina, gridBagConstraints);

        btnPechar.setText("Pechar");
        pnlBotons.add(btnPechar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(pnlBotons, gridBagConstraints);

        cmbPropietarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPropietariosItemStateChanged(evt);
            }
        });
        cmbPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPropietariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cmbPropietarios, gridBagConstraints);

        cmbCans.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCansItemStateChanged(evt);
            }
        });
        cmbCans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCansActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cmbCans, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCansActionPerformed

    private void cmbCansItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCansItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCansItemStateChanged

    private void cmbPropietariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPropietariosItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbPropietariosItemStateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPropietariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPropietariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnPechar;
    private javax.swing.JButton btnVacinar;
    private javax.swing.JComboBox<String> cmbCans;
    private javax.swing.JComboBox<String> cmbPropietarios;
    private javax.swing.JComboBox<String> cmbVacinas;
    private javax.swing.JLabel lblCan;
    private javax.swing.JLabel lblChip;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblObservacions;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblVacina;
    private javax.swing.JPanel pnlAplicarVacina;
    private javax.swing.JPanel pnlBotons;
    private javax.swing.JPanel pnlVacinasAplicadas;
    private javax.swing.JScrollPane scpVacinacions;
    private javax.swing.JTable tblVacinacions;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtObservacions;
    // End of variables declaration//GEN-END:variables
}
