package pojos;
// Generated 28 ene. 2025 10:01:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

    @Id
    @Column(name = "Num_departamento")
    private int numDepartamento;
    @Column(name = "Nome_departamento")
    private String nomeDepartamento;

    public Departamento() {
    }

    public Departamento(int numDepartamento, String nomeDepartamento) {
        this.numDepartamento = numDepartamento;
        this.nomeDepartamento = nomeDepartamento;
    }

    public int getNumDepartamento() {
        return this.numDepartamento;
    }

    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }

    public String getNomeDepartamento() {
        return this.nomeDepartamento;
    }

    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }


}


