package pojos;
// Generated 28 ene. 2025 10:01:41 by Hibernate Tools 4.3.1


import org.hibernate.annotations.CollectionId;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.SortedMap;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

    @Id
    @Column(name = "Num_departamento")
    private int numDepartamento;

    @Column(name = "Nome_departamento")
    private String nomeDepartamento;

    @ManyToOne
    @JoinColumn(name = "Director")
    private Empregado director;

    /* Mapeo de los lugares como ibag de componente*/
    @ElementCollection
    @CollectionTable(name = "lugar", joinColumns = @JoinColumn(name = "Num_departamento"))
    @GenericGenerator(name = "increment", strategy = "increment")
    @CollectionId(columns = @Column(name = "ID"), generator = "increment", type = @Type(type = "int"))
    @Column(name = "lugar", nullable = false)
    //@GeneratedValue(strategy = GenerationType.IDENTITY)
    @OrderColumn(name = "ID")
    private Collection<String> lugares = new ArrayList<>();

    //Mapeo de los proyectos que controla
    private Collection<Proxecto> proxectos = new ArrayList<>();

    public Departamento() {
    }

    public Departamento(int numDepartamento, String nomeDepartamento) {
        this.numDepartamento = numDepartamento;
        this.nomeDepartamento = nomeDepartamento;
    }

    public Departamento(int numDepartamento, String nomeDepartamento, Empregado director) {
        this.numDepartamento = numDepartamento;
        this.nomeDepartamento = nomeDepartamento;
        this.director = director;
    }

    public int getNumDepartamento() {
        return this.numDepartamento;
    }

    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }

    public String getNomeDepartamento() {
        return this.nomeDepartamento;
    }

    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    public Collection<String> getLugares() {
        return lugares;
    }

    public void setLugares(Collection<String> lugares) {
        this.lugares = lugares;
    }

    public Empregado getDirector() {
        return director;
    }

    public void setDirector(Empregado director) {
        this.director = director;
    }

    public Collection<Proxecto> getProxectos() {
        return proxectos;
    }

    public void setProxectos(Collection<Proxecto> proxectos) {
        this.proxectos = proxectos;
    }
}


