package pojos;
// Generated 28 ene. 2025 10:01:41 by Hibernate Tools 4.3.1


import javax.naming.Name;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Proxecto generated by hbm2java
 */
@Entity
@Table (name = "proxecto")
public class Proxecto implements java.io.Serializable {

    @Id
    @Column(name = "Num_proxecto")
    private int numProxecto;

    @Column(name = "Nome_proxecto")
    private String nomeProxecto;

    @Column(name = "Lugar")
    private String lugar;

    @ManyToOne
    @JoinColumn(name = "NumDepartControla")
    private Departamento numDepartControla;

    private Set<Empregado> empregados = new HashSet<>();

    public Departamento getNumDepartControla() {
        return numDepartControla;
    }

    public void setNumDepartControla(Departamento numDepartControla) {
        this.numDepartControla = numDepartControla;
    }

    public Proxecto() {
    }

    public Proxecto(int numProxecto, String nomeProxecto, String lugar) {
        this.numProxecto = numProxecto;
        this.nomeProxecto = nomeProxecto;
        this.lugar = lugar;
    }

    public int getNumProxecto() {
        return this.numProxecto;
    }

    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }

    public String getNomeProxecto() {
        return this.nomeProxecto;
    }

    public void setNomeProxecto(String nomeProxecto) {
        this.nomeProxecto = nomeProxecto;
    }

    public String getLugar() {
        return this.lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    public Set<Empregado> getEmpregados() {
        return empregados;
    }

    public void setEmpregados(Set<Empregado> empregados) {
        this.empregados = empregados;
    }
}