package pojos;
// Generated 28 ene. 2025 10:01:41 by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.*;

/**
 * Proxecto generated by hbm2java
 */
@Entity
@Table (name = "proxecto")
public class Proxecto implements java.io.Serializable {

    @Id
    @Column(name = "Num_proxecto")
    private int numProxecto;

    @Column(name = "Nome_proxecto")
    private String nomeProxecto;

    @Column(name = "Lugar")
    private String lugar;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "NumDepartControla", nullable = false)
    private Departamento departamento;

    //@ManyToMany(mappedBy = "proxecto")
    @ManyToMany
    @JoinTable(name = "empregado_proxecto",
            joinColumns = @JoinColumn(name = "NumProxecto"),
            inverseJoinColumns = @JoinColumn(name = "NSS_Empregado"))
    private Set<Empregado> empregados = new HashSet<>();

    public Departamento getDepartamento() {
        return departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    public Proxecto() {
    }

    public Proxecto(int numProxecto, String nomeProxecto, String lugar) {
        this.numProxecto = numProxecto;
        this.nomeProxecto = nomeProxecto;
        this.lugar = lugar;
    }

    public int getNumProxecto() {
        return this.numProxecto;
    }

    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }

    public String getNomeProxecto() {
        return this.nomeProxecto;
    }

    public void setNomeProxecto(String nomeProxecto) {
        this.nomeProxecto = nomeProxecto;
    }

    public String getLugar() {
        return this.lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    public Set<Empregado> getEmpregados() {
        return empregados;
    }

    public void setEmpregados(Set<Empregado> empregados) {
        this.empregados = empregados;
    }

}