package POJOS;
// Generated 09-feb-2023 8:57:23 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.List;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

    private int codigo;
    private String nome;
    private Integer horas;
    //mapeo de las ediciones de un curso
    private List<Edicion> edicions = new ArrayList();

    public Curso() {
    }

    public Curso(int codigo, String nome) {
        this.codigo = codigo;
        this.nome = nome;
    }

    public Curso(String nome, Integer horas) {
        this.nome = nome;
        this.horas = horas;
    }

    

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getHoras() {
        return this.horas;
    }

    public void setHoras(Integer horas) {
        this.horas = horas;
    }

    public List<Edicion> getEdicions() {
        return edicions;
    }

    public void setEdicions(List<Edicion> edicions) {
        this.edicions = edicions;
    }

    

}
