package POJOS;
// Generated 09-feb-2023 8:57:23 by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {
    private int numDepartamento;
    private String nomeDepartamento;
    // el empleado fijo que es director 
    private Empregadofixo director;

    // D.1
    // empregados que pertenecen a un departamento
    private Set<Empregado> empregados = new HashSet(0);

    //mapeo de los lugares con coleccion Idbag
    private Collection<String> lugares = new ArrayList();
    //mapeo de los proyectosque controla un departamento
    private Collection<Proxecto> proxectos = new ArrayList();

    public Departamento() {
    }

    public int getNumDepartamento() {
        return numDepartamento;
    }

    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }

    public String getNomeDepartamento() {
        return nomeDepartamento;
    }

    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    public Empregadofixo getDirector() {
        return director;
    }

    public void setDirector(Empregadofixo director) {
        this.director = director;
    }

    public Set<Empregado> getEmpregados() {
        return empregados;
    }

    public void setEmpregados(Set<Empregado> empregados) {
        this.empregados = empregados;
    }

    public Collection<String> getLugares() {
        return lugares;
    }

    public void setLugares(Collection<String> lugares) {
        this.lugares = lugares;
    }

    public Collection<Proxecto> getProxectos() {
        return proxectos;
    }

    public void setProxectos(Collection<Proxecto> proxectos) {
        this.proxectos = proxectos;
    }

}