package POJOS;
// Generated 09-feb-2023 8:57:23 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedMap;
import java.util.TreeMap;

/**
 * Empregadofixo generated by hbm2java
 */
public class Empregadofixo extends Empregado implements java.io.Serializable {


    private Double salario;
    private Date dataAlta;
    private String categoria;
    // horas extras de un empleado fijo
    private SortedMap<Date, Double> horasextras = new TreeMap();
    // las ediciones que imparte un profesor
    private Set<Edicion> edicionprofesor = new HashSet(0);
     //departamentos que pueden ser director
    private Set<Departamento> deptodirector = new HashSet(0);

    public Empregadofixo() {
    }
  public Empregadofixo(String nss) {
        super(nss);
    }

    public Empregadofixo(String nss, String nome, String apelido1) {
        super(nss, nome, apelido1);
    }

    public Empregadofixo(Double salario, Date dataAlta, String categoria, String nss, String nome, String apelido1) {
        super(nss, nome, apelido1);
        this.salario = salario;
        this.dataAlta = dataAlta;
        this.categoria = categoria;
    }

    public Double getSalario() {
        return this.salario;
    }

    public void setSalario(Double salario) {
        this.salario = salario;
    }

    public Date getDataAlta() {
        return this.dataAlta;
    }

    public void setDataAlta(Date dataAlta) {
        this.dataAlta = dataAlta;
    }

    public String getCategoria() {
        return this.categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public Set<Edicion> getEdicionprofesor() {
        return edicionprofesor;
    }

    public void setEdicionprofesor(Set<Edicion> edicionprofesor) {
        this.edicionprofesor = edicionprofesor;
    }

    public SortedMap<Date, Double> getHorasextras() {
        return horasextras;
    }

    public void setHorasextras(SortedMap<Date, Double> horasextras) {
        this.horasextras = horasextras;
    }

    public Set<Departamento> getDeptodirector() {
        return deptodirector;
    }

    public void setDeptodirector(Set<Departamento> deptodirector) {
        this.deptodirector = deptodirector;
    }

}
