/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menudespregable;

import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class IntfMenuDespregable extends javax.swing.JFrame {

    /**
     * Creates new form IntfMenuDespregable
     */
    public IntfMenuDespregable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpcions = new javax.swing.JMenu();
        mnuOpcion1 = new javax.swing.JMenu();
        mnuitOpcion1_1 = new javax.swing.JMenuItem();
        mnuOpcion1_2 = new javax.swing.JMenu();
        mnuitOpcion1_2_1 = new javax.swing.JMenuItem();
        mnuitOpcion1_2_2 = new javax.swing.JMenuItem();
        mnuitOpcion2 = new javax.swing.JMenuItem();
        mnuitOpcion3 = new javax.swing.JMenuItem();
        mnuspSeparador = new javax.swing.JPopupMenu.Separator();
        mnuitResumo = new javax.swing.JMenuItem();
        mnuspSeparador2 = new javax.swing.JPopupMenu.Separator();
        mnuitSair = new javax.swing.JMenuItem();
        mnuSexo = new javax.swing.JMenu();
        mnuitrbtHome = new javax.swing.JRadioButtonMenuItem();
        mnuitrbtMuller = new javax.swing.JRadioButtonMenuItem();
        mnuIdiomas = new javax.swing.JMenu();
        mnuitchkAleman = new javax.swing.JCheckBoxMenuItem();
        mnuitchkFrances = new javax.swing.JCheckBoxMenuItem();
        mnuitchkIngles = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuOpcions.setText("Opcións");

        mnuOpcion1.setText("Opción 1");

        mnuitOpcion1_1.setText("Opción 1.1");
        mnuitOpcion1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitOpcion1_1ActionPerformed(evt);
            }
        });
        mnuOpcion1.add(mnuitOpcion1_1);

        mnuOpcion1_2.setText("Opción 1.2");

        mnuitOpcion1_2_1.setText("Opción 1.2.1");
        mnuOpcion1_2.add(mnuitOpcion1_2_1);

        mnuitOpcion1_2_2.setText("Opción 1.2.2");
        mnuOpcion1_2.add(mnuitOpcion1_2_2);

        mnuOpcion1.add(mnuOpcion1_2);

        mnuOpcions.add(mnuOpcion1);

        mnuitOpcion2.setText("Opción 2");
        mnuOpcions.add(mnuitOpcion2);

        mnuitOpcion3.setText("Opción 3");
        mnuOpcions.add(mnuitOpcion3);
        mnuOpcions.add(mnuspSeparador);

        mnuitResumo.setText("Resumo");
        mnuitResumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitResumoActionPerformed(evt);
            }
        });
        mnuOpcions.add(mnuitResumo);
        mnuOpcions.add(mnuspSeparador2);

        mnuitSair.setText("Saír");
        mnuitSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitSairActionPerformed(evt);
            }
        });
        mnuOpcions.add(mnuitSair);

        jMenuBar1.add(mnuOpcions);

        mnuSexo.setText("Sexo");

        buttonGroup1.add(mnuitrbtHome);
        mnuitrbtHome.setSelected(true);
        mnuitrbtHome.setText("Home");
        mnuitrbtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitrbtHomeActionPerformed(evt);
            }
        });
        mnuSexo.add(mnuitrbtHome);

        buttonGroup1.add(mnuitrbtMuller);
        mnuitrbtMuller.setText("Muller");
        mnuitrbtMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitrbtMullerActionPerformed(evt);
            }
        });
        mnuSexo.add(mnuitrbtMuller);

        jMenuBar1.add(mnuSexo);

        mnuIdiomas.setText("Idiomas");

        mnuitchkAleman.setText("Alemán");
        mnuitchkAleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitchkAlemanActionPerformed(evt);
            }
        });
        mnuIdiomas.add(mnuitchkAleman);

        mnuitchkFrances.setText("Francés");
        mnuitchkFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitchkFrancesActionPerformed(evt);
            }
        });
        mnuIdiomas.add(mnuitchkFrances);

        mnuitchkIngles.setText("Inglés");
        mnuitchkIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitchkInglesActionPerformed(evt);
            }
        });
        mnuIdiomas.add(mnuitchkIngles);

        jMenuBar1.add(mnuIdiomas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuitSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuitSairActionPerformed

    private void mnuitrbtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitrbtHomeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "A opción Home foi seleccionada");
    }//GEN-LAST:event_mnuitrbtHomeActionPerformed

    private void mnuitOpcion1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitOpcion1_1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Opción 1.1 seleccionada");
    }//GEN-LAST:event_mnuitOpcion1_1ActionPerformed

    private void mnuitrbtMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitrbtMullerActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "A opción Muller foi seleccionada");
    }//GEN-LAST:event_mnuitrbtMullerActionPerformed

    private void mnuitchkAlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitchkAlemanActionPerformed
        // TODO add your handling code here:
        if (mnuitchkAleman.isSelected()) {
            JOptionPane.showMessageDialog(this, "A opción Alemán foi marcada");
        } else {
            JOptionPane.showMessageDialog(this, "A opción Alemán foi desmarcada");
        }
    }//GEN-LAST:event_mnuitchkAlemanActionPerformed

    private void mnuitchkFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitchkFrancesActionPerformed
        // TODO add your handling code here:
        if (mnuitchkFrances.isSelected()) {
            JOptionPane.showMessageDialog(this, "A opción Francés foi marcada");
        } else {
            JOptionPane.showMessageDialog(this, "A opción Francés foi desmarcada");
        }
    }//GEN-LAST:event_mnuitchkFrancesActionPerformed

    private void mnuitchkInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitchkInglesActionPerformed
        // TODO add your handling code here:
        if (mnuitchkIngles.isSelected()) {
            JOptionPane.showMessageDialog(this, "A opción Inglés foi marcada");
        } else {
            JOptionPane.showMessageDialog(this, "A opción Inglés foi desmarcada");
        }
    }//GEN-LAST:event_mnuitchkInglesActionPerformed

    private void mnuitResumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitResumoActionPerformed
        // TODO add your handling code here:
        String sexo = "SEXO: ";
        if (mnuitrbtHome.isSelected()) {
            sexo += "Home";
        } else {
            sexo += "Muller";
        }
        String idiomas = "IDIOMAS: ";
        if (mnuitchkAleman.isSelected()) {
            idiomas += "Alemán ";
        }
        if (mnuitchkFrances.isSelected()) {
            idiomas += "Francés ";
        }
        if (mnuitchkIngles.isSelected()) {
            idiomas += "Inglés ";
        }
        if (idiomas.compareTo("IDIOMAS: ") == 0) {
            sexo += "\nIDIOMAS: Ningún";
        } else {
            sexo += "\n" + idiomas;
        }
        JOptionPane.showMessageDialog(this, sexo);
    }//GEN-LAST:event_mnuitResumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntfMenuDespregable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntfMenuDespregable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntfMenuDespregable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntfMenuDespregable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntfMenuDespregable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuIdiomas;
    private javax.swing.JMenu mnuOpcion1;
    private javax.swing.JMenu mnuOpcion1_2;
    private javax.swing.JMenu mnuOpcions;
    private javax.swing.JMenu mnuSexo;
    private javax.swing.JMenuItem mnuitOpcion1_1;
    private javax.swing.JMenuItem mnuitOpcion1_2_1;
    private javax.swing.JMenuItem mnuitOpcion1_2_2;
    private javax.swing.JMenuItem mnuitOpcion2;
    private javax.swing.JMenuItem mnuitOpcion3;
    private javax.swing.JMenuItem mnuitResumo;
    private javax.swing.JMenuItem mnuitSair;
    private javax.swing.JCheckBoxMenuItem mnuitchkAleman;
    private javax.swing.JCheckBoxMenuItem mnuitchkFrances;
    private javax.swing.JCheckBoxMenuItem mnuitchkIngles;
    private javax.swing.JRadioButtonMenuItem mnuitrbtHome;
    private javax.swing.JRadioButtonMenuItem mnuitrbtMuller;
    private javax.swing.JPopupMenu.Separator mnuspSeparador;
    private javax.swing.JPopupMenu.Separator mnuspSeparador2;
    // End of variables declaration//GEN-END:variables
}
