/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multixanela;

import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class IntfMultixanela extends javax.swing.JFrame {

    /**
     * Creates new form IntfMultixanela
     */
    public IntfMultixanela() {
        initComponents();
    }

    public void xanelasDatosPersoaisEnCascada() {
        Vector xanelasDatosPersoais = XestorDeXanelas.recuperarXanelasDatosPersoais();
        int posX = 10, posY = 10, incremento = 50;
        for (int i = 0; i < xanelasDatosPersoais.size(); i++) {
            DlgDatosPersoais xanela = (DlgDatosPersoais) xanelasDatosPersoais.elementAt(i);
            xanela.setLocation(posX, posY);
            posX += incremento;
            posY += incremento;
        }
    }

    public void xestionDeMensaxesDeErro(int numErro) {
        switch (numErro) {
            case 1:
                JOptionPane.showMessageDialog(this, "O nome non pode estar baleiro");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Os apelidos non poden estar baleiros");
                break;
        }
    }

    public void xestionDeMensaxesDeGraoAcadado(int grao) {
        switch (grao) {
            case 1:
                JOptionPane.showMessageDialog(this, "O máximo grao que acadou vostede e ESO");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "O máximo grao que acadou vostede e Bachalerato");
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "O máximo grao que acadou vostede e FP");
                break;
            case 4:
                JOptionPane.showMessageDialog(this, "O máximo grao que acadou vostede e Universidade");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Datos persoais");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("Datos académicos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setText("Saír");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jButton3, gridBagConstraints);

        jButton4.setText("Cascada");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jButton4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (XestorDeXanelas.abrirXanelasDatosPersoais()) {
            DlgDatosPersoais dlgDatosPersoais = new DlgDatosPersoais(this, false);
            XestorDeXanelas.engadirXanelaDatosPersoais(dlgDatosPersoais);
            dlgDatosPersoais.setVisible(true);
            dlgDatosPersoais.setSize(400, 200);
        } else {
            JOptionPane.showMessageDialog(this, "Non é posible abrir máis xanelas deste tipo");
            return;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (XestorDeXanelas.abrirXanelasDatosAcademicos()) {
            DlgDatosAcademicos dlgDatosAcademicos = new DlgDatosAcademicos(this, false);
            dlgDatosAcademicos.setVisible(true);
            dlgDatosAcademicos.setSize(400, 200);
            dlgDatosAcademicos.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Non é posible abrir máis xanelas deste tipo");
            return;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        xanelasDatosPersoaisEnCascada();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntfMultixanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
