/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multixanelaII;

/**
 *
 * @author usuario
 */
public class IntfMultixanelaII extends javax.swing.JFrame {

    /**
     * Creates new form IntfMultixanelaII
     */
    public IntfMultixanelaII() {
        initComponents();
    }

    public void engadirInfoNovoUsuario(Usuario usuario) {
        txtarInformacion.setText(usuario.toString() + "\n" + txtarInformacion.getText());
    }

    int idUsuario = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnNovoUsuario = new javax.swing.JButton();
        pnlInformacion = new javax.swing.JPanel();
        scrpnlInformacion = new javax.swing.JScrollPane();
        txtarInformacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(360, 40, 160, 24);

        btnNovoUsuario.setText("Novo Usuario");
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoUsuario);
        btnNovoUsuario.setBounds(360, 10, 160, 24);

        pnlInformacion.setLayout(new java.awt.BorderLayout());

        txtarInformacion.setColumns(20);
        txtarInformacion.setRows(5);
        txtarInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Información dos usuarios creados"));
        scrpnlInformacion.setViewportView(txtarInformacion);

        pnlInformacion.add(scrpnlInformacion, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlInformacion);
        pnlInformacion.setBounds(10, 10, 340, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        // TODO add your handling code here:
        DlgDatosNovoUsuario dlgDatosNovoUsuario = new DlgDatosNovoUsuario(this, false, idUsuario);
        // Chapuza para que incremente el contador
        idUsuario++;
        dlgDatosNovoUsuario.setLocationRelativeTo(null);
        dlgDatosNovoUsuario.setVisible(true);
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanelaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanelaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanelaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntfMultixanelaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntfMultixanelaII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JScrollPane scrpnlInformacion;
    private javax.swing.JTextArea txtarInformacion;
    // End of variables declaration//GEN-END:variables
}
